In [1]:
#导包
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 1.Pandas 基础操作

In [2]:
#调用数据
data = pd.read_csv('C:/Users/35986/Desktop/stock_day.csv')
print(pd.DataFrame(data))
#数据清洗
print('----------------------------')
data.drop(columns=['ma5', 'ma10','ma20','v_ma5','v_ma10','v_ma20'],axis=0, inplace=True)#删除不需要的列
print(data)

             open   high  close    low     volume  price_change  p_change  \
2018-02-27  23.53  25.88  24.16  23.53   95578.03          0.63      2.68
2018-02-26  22.80  23.78  23.53  22.80   60985.11          0.69      3.02
2018-02-23  22.88  23.37  22.82  22.71   52914.01          0.54      2.42
2018-02-22  22.25  22.76  22.28  22.02   36105.01          0.36      1.64
2018-02-14  21.49  21.99  21.92  21.48   23331.04          0.44      2.05
...           ...    ...    ...    ...        ...           ...       ...
2015-03-06  13.17  14.48  14.28  13.13  179831.72          1.12      8.51
2015-03-05  12.88  13.45  13.16  12.87   93180.39          0.26      2.02
2015-03-04  12.80  12.92  12.90  12.61   67075.44          0.20      1.57
2015-03-03  12.52  13.06  12.70  12.52  139071.61          0.18      1.44
2015-03-02  12.25  12.67  12.52  12.20   96291.73          0.32      2.62

               ma5    ma10    ma20      v_ma5     v_ma10     v_ma20  turnover
2018-02-27  22.942  22.142  22.875   53782.64   46738.65   55576.11      2.39
2018-02-26  22.406  21.955  22.942   40827.52   42736.34   56007.50      1.53
2018-02-23  21.938  21.929  23.022   35119.58   41871.97   56372.85      1.32
2018-02-22  21.446  21.909  23.137   35397.58   39904.78   60149.60      0.90
2018-02-14  21.366  21.923  23.253   33590.21   42935.74   61716.11      0.58
...            ...     ...     ...        ...        ...        ...       ...
2015-03-06  13.112  13.112  13.112  115090.18  115090.18  115090.18      6.16
2015-03-05  12.820  12.820  12.820   98904.79   98904.79   98904.79      3.19
2015-03-04  12.707  12.707  12.707  100812.93  100812.93  100812.93      2.30
2015-03-03  12.610  12.610  12.610  117681.67  117681.67  117681.67      4.76
2015-03-02  12.520  12.520  12.520   96291.73   96291.73   96291.73      3.30

[643 rows x 14 columns]
----------------------------
             open   high  close    low     volume  price_change  p_change  \
2018-02-27  23.53  25.88  24.16  23.53   95578.03          0.63      2.68
2018-02-26  22.80  23.78  23.53  22.80   60985.11          0.69      3.02
2018-02-23  22.88  23.37  22.82  22.71   52914.01          0.54      2.42
2018-02-22  22.25  22.76  22.28  22.02   36105.01          0.36      1.64
2018-02-14  21.49  21.99  21.92  21.48   23331.04          0.44      2.05
...           ...    ...    ...    ...        ...           ...       ...
2015-03-06  13.17  14.48  14.28  13.13  179831.72          1.12      8.51
2015-03-05  12.88  13.45  13.16  12.87   93180.39          0.26      2.02
2015-03-04  12.80  12.92  12.90  12.61   67075.44          0.20      1.57
2015-03-03  12.52  13.06  12.70  12.52  139071.61          0.18      1.44
2015-03-02  12.25  12.67  12.52  12.20   96291.73          0.32      2.62

            turnover
2018-02-27      2.39
2018-02-26      1.53
2018-02-23      1.32
2018-02-22      0.90
2018-02-14      0.58
...              ...
2015-03-06      6.16
2015-03-05      3.19
2015-03-04      2.30
2015-03-03      4.76
2015-03-02      3.30

[643 rows x 8 columns]

### 1.2 索引操作

In [3]:
#1:Find data by rows and columns
print(data['open'])
print('----------------------------')
print(data['open']['2018-01-02'])

2018-02-27    23.53
2018-02-26    22.80
2018-02-23    22.88
2018-02-22    22.25
2018-02-14    21.49
              ...
2015-03-06    13.17
2015-03-05    12.88
2015-03-04    12.80
2015-03-03    12.52
2015-03-02    12.25
Name: open, Length: 643, dtype: float64
----------------------------
22.3

In [4]:
# 2:loc() 行索引 和 列名
data.loc['2018-02-27','high']
print('----------------------------')
data.loc['2018-02-27':'2018-02-20','open':'high']

----------------------------

             open   high
2018-02-27  23.53  25.88
2018-02-26  22.80  23.78
2018-02-23  22.88  23.37
2018-02-22  22.25  22.76

In [5]:
#3:iloc() 行号 和 列索引  先行后列
print(data.iloc[0,1])

print('----------------------------')
print(data.iloc[0:5,1:4])

25.88
----------------------------
             high  close    low
2018-02-27  25.88  24.16  23.53
2018-02-26  23.78  23.53  22.80
2018-02-23  23.37  22.82  22.71
2018-02-22  22.76  22.28  22.02
2018-02-14  21.99  21.92  21.48

In [6]:
#赋值
data.loc['2018-02-27','high'] = 100
print(data.loc['2018-02-27','high'])

100.0

In [7]:
#基于open 做升序
print(data.sort_values(by='open',ascending=True))

             open   high  close    low     volume  price_change  p_change  \
2015-03-02  12.25  12.67  12.52  12.20   96291.73          0.32      2.62
2015-09-02  12.30  14.11  12.36  12.30   70201.74         -1.10     -8.17
2015-03-03  12.52  13.06  12.70  12.52  139071.61          0.18      1.44
2015-03-04  12.80  12.92  12.90  12.61   67075.44          0.20      1.57
2015-03-05  12.88  13.45  13.16  12.87   93180.39          0.26      2.02
...           ...    ...    ...    ...        ...           ...       ...
2015-06-11  33.17  34.98  34.39  32.51  173075.73          0.54      1.59
2017-11-01  33.85  34.34  33.83  33.10  232325.30         -0.61     -1.77
2015-06-10  34.10  36.35  33.85  32.23  269033.12          0.51      1.53
2015-06-12  34.69  35.98  35.21  34.01  159825.88          0.82      2.38
2015-06-15  34.99  34.99  31.69  31.69  199369.53         -3.52    -10.00

            turnover
2015-03-02      3.30
2015-09-02      2.40
2015-03-03      4.76
2015-03-04      2.30
2015-03-05      3.19
...              ...
2015-06-11      5.92
2017-11-01      5.81
2015-06-10      9.21
2015-06-12      5.47
2015-06-15      6.82

[643 rows x 8 columns]

In [8]:
data.sort_values(by=['open','high'],ascending=[True,True])

,open,high,close,low,volume,price_change,p_change,turnover
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,3.30
2015-09-02,12.30,14.11,12.36,12.30,70201.74,-1.10,-8.17,2.40
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,4.76
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,2.30
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,3.19
...,...,...,...,...,...,...,...,...
2015-06-11,33.17,34.98,34.39,32.51,173075.73,0.54,1.59,5.92
2017-11-01,33.85,34.34,33.83,33.10,232325.30,-0.61,-1.77,5.81
2015-06-10,34.10,36.35,33.85,32.23,269033.12,0.51,1.53,9.21
2015-06-12,34.69,35.98,35.21,34.01,159825.88,0.82,2.38,5.47
2015-06-15,34.99,34.99,31.69,31.69,199369.53,-3.52,-10.00,6.82

In [9]:
data.sort_index(ascending=True)#基于行索引升序

,open,high,close,low,volume,price_change,p_change,turnover
2015-03-02,12.25,12.67,12.52,12.20,96291.73,0.32,2.62,3.30
2015-03-03,12.52,13.06,12.70,12.52,139071.61,0.18,1.44,4.76
2015-03-04,12.80,12.92,12.90,12.61,67075.44,0.20,1.57,2.30
2015-03-05,12.88,13.45,13.16,12.87,93180.39,0.26,2.02,3.19
2015-03-06,13.17,14.48,14.28,13.13,179831.72,1.12,8.51,6.16
...,...,...,...,...,...,...,...,...
2018-02-14,21.49,21.99,21.92,21.48,23331.04,0.44,2.05,0.58
2018-02-22,22.25,22.76,22.28,22.02,36105.01,0.36,1.64,0.90
2018-02-23,22.88,23.37,22.82,22.71,52914.01,0.54,2.42,1.32
2018-02-26,22.80,23.78,23.53,22.80,60985.11,0.69,3.02,1.53
2018-02-27,23.53,100.00,24.16,23.53,95578.03,0.63,2.68,2.39

In [10]:
print(data.open.sort_values(ascending=True))#基于open列升序
print('----------------------------')
print(data.open.sort_index(ascending=True))

2015-03-02    12.25
2015-09-02    12.30
2015-03-03    12.52
2015-03-04    12.80
2015-03-05    12.88
              ...
2015-06-11    33.17
2017-11-01    33.85
2015-06-10    34.10
2015-06-12    34.69
2015-06-15    34.99
Name: open, Length: 643, dtype: float64
----------------------------
2015-03-02    12.25
2015-03-03    12.52
2015-03-04    12.80
2015-03-05    12.88
2015-03-06    13.17
              ...
2018-02-14    21.49
2018-02-22    22.25
2018-02-23    22.88
2018-02-26    22.80
2018-02-27    23.53
Name: open, Length: 643, dtype: float64

## 2.算法运算

In [11]:
print(data.close)
print('----------------------------')
print(data.close + 2)

2018-02-27    24.16
2018-02-26    23.53
2018-02-23    22.82
2018-02-22    22.28
2018-02-14    21.92
              ...
2015-03-06    14.28
2015-03-05    13.16
2015-03-04    12.90
2015-03-03    12.70
2015-03-02    12.52
Name: close, Length: 643, dtype: float64
----------------------------
2018-02-27    26.16
2018-02-26    25.53
2018-02-23    24.82
2018-02-22    24.28
2018-02-14    23.92
              ...
2015-03-06    16.28
2015-03-05    15.16
2015-03-04    14.90
2015-03-03    14.70
2015-03-02    14.52
Name: close, Length: 643, dtype: float64

In [12]:
#筛选
print(data.open[data.open > 23])
print('----------------------------')
print(data[(data.open > 23) & (data.close < 24)])

2018-02-27    23.53
2018-02-01    23.71
2018-01-31    23.85
2018-01-30    23.71
2018-01-29    24.40
              ...
2015-05-21    27.50
2015-05-20    24.10
2015-05-19    23.68
2015-04-16    24.63
2015-04-15    23.45
Name: open, Length: 184, dtype: float64
----------------------------
             open   high  close    low     volume  price_change  p_change  \
2018-02-01  23.71  23.86  22.42  22.22   66414.64         -1.30     -5.48
2018-01-31  23.85  23.98  23.72  23.31   49155.02         -0.11     -0.46
2018-01-30  23.71  24.08  23.83  23.70   32420.43          0.05      0.21
2018-01-29  24.40  24.63  23.77  23.72   65469.81         -0.73     -2.98
2018-01-15  24.01  24.23  23.43  23.30   69768.17         -0.80     -3.30
2018-01-11  23.67  23.85  23.67  23.21   48525.75         -0.12     -0.50
2018-01-10  24.10  24.60  23.80  23.40   70125.79         -0.14     -0.58
2018-01-09  24.60  24.78  23.96  23.82   82175.82         -0.76     -3.07
2017-12-22  23.21  23.39  22.99  22.90   28394.00         -0.21     -0.91
2017-12-21  23.39  23.50  23.21  22.86   34005.55         -0.11     -0.47
2017-12-20  23.61  23.96  23.33  23.20   43368.92         -0.14     -0.60
2017-12-19  23.23  23.66  23.46  23.23   43068.70          0.31      1.34
2017-12-15  23.40  23.40  23.00  22.85   43442.15         -0.46     -1.96
2017-12-14  23.65  23.77  23.47  23.22   45061.12         -0.33     -1.39
2017-12-13  23.99  24.38  23.81  23.60   68659.12         -0.15     -0.63
2017-12-04  23.91  24.15  22.92  22.85   85482.80         -1.27     -5.25
2017-09-05  23.76  24.32  23.95  23.31  138987.19          0.19      0.80
2017-09-04  24.45  24.45  23.76  23.30  244004.84         -1.28     -5.11
2017-08-29  23.45  23.85  23.06  23.04   90952.18         -0.44     -1.87
2017-08-28  23.45  23.70  23.50  23.05  119146.78          0.13      0.56
2017-08-23  23.90  24.06  23.07  22.85  264518.94         -1.28     -5.26
2017-07-27  23.39  23.39  22.76  22.63  101811.01         -0.64     -2.73
2017-07-26  23.53  23.92  23.40  22.85  110276.48         -0.30     -1.27
2017-07-25  23.07  24.20  23.70  22.64  167489.48          0.67      2.91
2017-07-14  23.28  24.29  22.87  22.80  163954.17         -0.60     -2.56
2017-07-13  23.60  23.60  23.47  22.81  175621.84         -0.34     -1.43
2017-06-27  23.10  23.24  22.20  22.06  288556.75         -1.06     -4.56
2017-06-26  23.30  23.87  23.26  22.57  282271.66         -0.08     -0.34
2017-06-23  24.00  24.47  23.34  23.34  438271.69         -2.59     -9.99
2016-11-29  25.00  25.10  22.87  22.87  190253.05         -2.54    -10.00
2016-11-07  23.11  23.39  23.06  22.84   44069.47         -0.33     -1.41
2016-11-04  23.17  23.65  23.30  22.80   57950.55          0.09      0.39
2016-11-03  23.16  23.51  23.20  22.65  108786.66          0.13      0.56
2016-11-02  23.80  23.99  23.10  23.00  105628.11         -0.78     -3.27
2016-11-01  24.10  24.60  23.90  23.63  104329.24         -0.35     -1.44
2016-10-28  24.10  24.20  23.89  23.05   96994.48         -0.15     -0.62
2016-09-09  23.92  24.06  23.08  22.60  182559.94         -1.14     -4.71
2015-12-28  23.20  23.40  21.89  21.85   71790.53         -1.31     -5.65
2015-12-25  23.18  23.30  23.19  22.82   46800.90          0.15      0.65
2015-12-24  24.05  24.05  23.05  22.88   75142.68         -1.06     -4.40
2015-12-22  23.80  24.10  23.80  23.50   53460.38         -0.11     -0.46
2015-12-21  24.20  24.80  23.95  23.70   67320.60         -0.04     -0.17
2015-12-18  23.53  24.66  23.99  23.43  109230.05          0.65      2.79
2015-11-27  23.35  23.43  21.17  21.17   96648.60         -2.35     -9.99
2015-11-26  23.85  24.08  23.53  23.50   51446.29         -0.31     -1.30
2015-11-25  23.40  24.15  23.85  23.40   67009.81          0.23      0.97
2015-11-24  23.26  23.75  23.64  22.86   65186.31          0.33      1.42
2015-11-23  24.55  24.61  23.30  23.25   87312.13         -0.90     -3.72
2015-11-19  23.72  24.26  23.91  23.01  120660.59         -0.12     -0.50
2015-10-26  23.32  23.46  21.85  21.06  178488.00         -0.58     -2.59
2015-07-24  24.00  24.55  22.99  22.38  132799.91         -1.15     -4.76
2015-07-01  25.00  25.80  23.27  22.80  124199.99         -1.74     -6.96
2015-06-29  26.50  26.98  23.83  22.82  168452.12         -1.45     -5.74
2015-05-19  23.68  23.69  23.32  22.47   82945.73          0.25      1.08
2015-04-16  24.63  25.21  22.97  21.94  221070.31         -1.41     -5.78

            turnover
2018-02-01      1.66
2018-01-31      1.23
2018-01-30      0.81
2018-01-29      1.64
2018-01-15      1.75
2018-01-11      1.21
2018-01-10      1.76
2018-01-09      2.06
2017-12-22      0.71
2017-12-21      0.85
2017-12-20      1.09
2017-12-19      1.08
2017-12-15      1.09
2017-12-14      1.13
2017-12-13      1.72
2017-12-04      2.14
2017-09-05      3.48
2017-09-04      6.11
2017-08-29      2.28
2017-08-28      2.98
2017-08-23      6.62
2017-07-27      2.55
2017-07-26      2.76
2017-07-25      4.19
2017-07-14      4.10
2017-07-13      4.40
2017-06-27      7.22
2017-06-26      7.06
2017-06-23     10.97
2016-11-29      4.76
2016-11-07      1.10
2016-11-04      1.45
2016-11-03      2.72
2016-11-02      2.64
2016-11-01      2.61
2016-10-28      2.43
2016-09-09      6.25
2015-12-28      2.46
2015-12-25      1.60
2015-12-24      2.57
2015-12-22      1.83
2015-12-21      2.30
2015-12-18      3.74
2015-11-27      3.31
2015-11-26      1.76
2015-11-25      2.29
2015-11-24      2.23
2015-11-23      2.99
2015-11-19      4.13
2015-10-26      6.11
2015-07-24      4.55
2015-07-01      4.25
2015-06-29      5.77
2015-05-19      2.84
2015-04-16      7.57

In [13]:
#固定值筛选open等于23.53 或者 close等于24.67
print(data[(data.open == 23.53) | (data.close == 24.67)])

             open    high  close    low     volume  price_change  p_change  \
2018-02-27  23.53  100.00  24.16  23.53   95578.03          0.63      2.68
2017-07-26  23.53   23.92  23.40  22.85  110276.48         -0.30     -1.27
2015-12-18  23.53   24.66  23.99  23.43  109230.05          0.65      2.79

            turnover
2018-02-27      2.39
2017-07-26      2.76
2015-12-18      3.74

In [14]:
#isin()方法筛选open等于23.53 或者 close等于24.67
print(data[data.open.isin([23.53]) | data.close.isin([24.67])])

             open    high  close    low     volume  price_change  p_change  \
2018-02-27  23.53  100.00  24.16  23.53   95578.03          0.63      2.68
2017-07-26  23.53   23.92  23.40  22.85  110276.48         -0.30     -1.27
2015-12-18  23.53   24.66  23.99  23.43  109230.05          0.65      2.79

            turnover
2018-02-27      2.39
2017-07-26      2.76
2015-12-18      3.74

###  3.统计运算

In [17]:
print(data.sum())#求和
print('----------------------------')
print(data.mean())#求平均值
print('----------------------------')
print(data.max())#求最大值
print('----------------------------')
print(data.high.sum())#求high列的和

open               13678.35
high               14156.15
close              13719.22
low                13356.29
volume          64239248.79
price_change          12.09
p_change             122.35
turnover            1887.97
dtype: float64
----------------------------
open               21.272706
high               22.015785
close              21.336267
low                20.771835
volume          99905.519114
price_change        0.018802
p_change            0.190280
turnover            2.936190
dtype: float64
----------------------------
open                34.99
high               100.00
close               35.21
low                 34.01
volume          501915.41
price_change         3.03
p_change            10.03
turnover            12.56
dtype: float64
----------------------------
14156.150000000001

In [18]:
#apply()方法对数据进行批量处理
def add_10(x):
    return x.max() - x.min() 
print(data[['open','close']])
print('----------------------------')
print(data[['open','close']].apply(add_10))

             open  close
2018-02-27  23.53  24.16
2018-02-26  22.80  23.53
2018-02-23  22.88  22.82
2018-02-22  22.25  22.28
2018-02-14  21.49  21.92
...           ...    ...
2015-03-06  13.17  14.28
2015-03-05  12.88  13.16
2015-03-04  12.80  12.90
2015-03-03  12.52  12.70
2015-03-02  12.25  12.52

[643 rows x 2 columns]
----------------------------
open     22.74
close    22.85
dtype: float64