In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
df = pd.read_csv('uniqlo.csv')

# 数据分组

In [ ]:
#agg  -> aggregate聚合
#格式 df.groupby(['分组1', '分组2'...]).agg({'列1': '函数1', '列2': '函数2'...})

In [3]:
#场景1：按照单列分组
df.groupby(['city'])

In [ ]:
#场景2：按照多列分组
df.groupby(['city', 'gender'])

In [7]:
#如何查看分组后的数据
#分组后的数据是一个DataFrameGroupBy对象，可以使用get_group方法查看某个分组的数据
#查看city为Beijing的分组数据
df.groupby(['city','channel']).get_group(('北京', '线下'))

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
9,21,北京,线下,Female,45-49,Weekend,毛衣,1,199.00,1,1,99
168,21,北京,线下,Female,35-39,Weekday,毛衣,3,447.00,3,3,99
175,21,北京,线下,Female,45-49,Weekend,配件,1,149.00,1,1,29
263,21,北京,线下,Male,20-24,Weekday,T恤,1,55.33,1,1,49
289,21,北京,线下,Female,35-39,Weekend,牛仔裤,1,199.00,1,1,69
...,...,...,...,...,...,...,...,...,...,...,...,...
22037,21,北京,线下,Female,20-24,Weekday,T恤,7,493.00,7,7,49
22110,21,北京,线下,Male,50-54,Weekend,当季新品,1,79.00,1,1,59
22192,21,北京,线下,Female,20-24,Weekday,T恤,7,693.00,7,7,49
22273,21,北京,线下,Female,20-24,Weekday,当季新品,2,288.00,2,2,59
22280,21,北京,线下,Female,35-39,Weekend,T恤,1,59.00,1,1,49

In [9]:
#场景4：分组后进行聚合
#按照city和销售渠道分组，计算每个分组的销售额
df.groupby(['city', 'channel']).agg({'revenue': 'sum'})

                revenue
city channel
上海   线上       114438.09
     线下       275383.64
北京   线下       130458.62
南京   线下       123150.93
广州   线上       200893.30
     线下       117231.19
成都   线下       208189.86
杭州   线下       589518.49
武汉   线上       281420.73
     线下       308357.05
深圳   线下       733123.68
西安   线上        30088.01
     线下       180686.61
重庆   线上        26330.35
     线下       237162.30

In [16]:
#分组过滤
#销售额平均大于200的分组

df.groupby('city').filter(lambda x: x.revenue.mean() > 200)

,store_id,city,channel,gender_group,age_group,wkd_ind,product,customer,revenue,order,quant,unit_cost
9,21,北京,线下,Female,45-49,Weekend,毛衣,1,199.0,1,1,99
23,19,南京,线下,Female,35-39,Weekend,T恤,4,176.0,4,4,49
40,19,南京,线下,Female,45-49,Weekday,毛衣,2,198.0,2,2,99
62,19,南京,线下,Female,35-39,Weekend,T恤,2,197.0,2,2,49
168,21,北京,线下,Female,35-39,Weekday,毛衣,3,447.0,3,3,99
...,...,...,...,...,...,...,...,...,...,...,...,...
22182,19,南京,线下,Female,30-34,Weekend,当季新品,1,79.0,1,1,59
22192,21,北京,线下,Female,20-24,Weekday,T恤,7,693.0,7,7,49
22251,19,南京,线下,Female,45-49,Weekend,短裤,1,39.0,1,1,19
22273,21,北京,线下,Female,20-24,Weekday,当季新品,2,288.0,2,2,59
22280,21,北京,线下,Female,35-39,Weekend,T恤,1,59.0,1,1,49